export const LOGGED_IN_SUCCESS = 'LOGGED_IN_SUCCESS';

export const LOGIN_API_SUCCESS = 'LOGIN_API_SUCCESS';
export const LOGIN_API_ERROR = 'LOGIN_API_ERROR';

export const SIGNOUT = 'SIGNOUT';

export const GET_PROFILE_API_SUCCESS = 'GET_PROFILE_API_SUCCESS';
export const GET_PROFILE_API_ERROR = 'GET_PROFILE_API_ERROR';

export const EDIT_PROFILE_API = 'EDIT_PROFILE_API';
export const EDIT_PROFILE_API_SUCCESS = 'EDIT_PROFILE_API_SUCCESS';
export const EDIT_PROFILE_API_ERROR = 'EDIT_PROFILE_API_ERROR';

export const PROFILE_UPLOAD_API = 'PROFILE_UPLOAD_API';

export const RESET_PASSWORD_API = 'RESET_PASSWORD_API';
export const VERIFY_CODE_API = 'VERIFY_CODE_API';
export const CHANGE_PASSWORD_API = 'CHANGE_PASSWORD_API';
