export const REGISTER_API_SUCCESS = 'REGISTER_API_SUCCESS';
export const REGISTER_API_ERROR = 'REGISTER_API_ERROR';

export const LOGIN_API_SUCCESS = 'LOGIN_API_SUCCESS';
export const LOGIN_API_ERROR = 'LOGIN_API_ERROR';
