export const CREATE_BUSINESS_API = 'CREATE_BUSINESS_API';
export const CREATE_BUSINESS_API_SUCCESS = 'CREATE_BUSINESS_API_SUCCESS';
export const CREATE_BUSINESS_API_ERROR = 'CREATE_BUSINESS_API_ERROR';

export const GET_POPULAR_BUSINESSES_API = 'GET_POPULAR_BUSINESSES_API';
export const GET_ALL_BUSINESSES_API = 'GET_ALL_BUSINESSES_API';
export const LOAD_MORE_ALL_BUSINESSES_API = 'LOAD_MORE_ALL_BUSINESSES_API';
export const GET_RECENTLY_ADDED_BUSINESSES_API =
  'GET_RECENTLY_ADDED_BUSINESSES_API';
export const GET_RECENTLY_ADDED_BUSINESSES_PLACE_DETAIL =
  'GET_RECENTLY_ADDED_BUSINESSES_PLACE_DETAIL';

export const SET_BUSINESS_FORM_DATA_IN_REDUX =
  'SET_BUSINESS_FORM_DATA_IN_REDUX';

export const GET_SINGLE_BUSINESS_API = 'GET_SINGLE_BUSINESS_API';
export const GET_RELATED_BUSINESS_API = 'GET_RELATED_BUSINESS_API';

export const ADD_REVIEW_API = 'ADD_REVIEW_API';
export const ADD_REVIEW_API_SUCCESS = 'ADD_REVIEW_API_SUCCESS';
export const ADD_REVIEW_API_ERROR = 'ADD_REVIEW_API_ERROR';

export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const UPLOAD_THUMBNAIL_IMAGE_API = 'UPLOAD_THUMBNAIL_IMAGE_API';
export const REMOVE_THUMBNAIL_IMAGES = 'REMOVE_THUMBNAIL_IMAGES';
export const UPLOAD_GALLERY_IMAGES_API = 'UPLOAD_GALLERY_IMAGES_API';
export const REMOVE_GALLERY_IMAGES = 'REMOVE_GALLERY_IMAGES';
