export const CREATE_BUSINESS_API = 'CREATE_BUSINESS_API';
export const CREATE_BUSINESS_API_SUCCESS = 'CREATE_BUSINESS_API_SUCCESS';
export const CREATE_BUSINESS_API_ERROR = 'CREATE_BUSINESS_API_ERROR';

export const GET_BUSINESSES_API = 'GET_BUSINESSES_API';

export const SET_BUSINESS_FORM_DATA_IN_REDUX = 'SET_BUSINESS_FORM_DATA_IN_REDUX';
