export const GET_FAVORITES_API = 'GET_FAVORITES_API';
export const GET_FAVORITES_API_SUCCESS = 'GET_FAVORITES_API_SUCCESS';
export const GET_FAVORITES_API_ERROR = 'GET_FAVORITES_API_ERROR';
export const ADD_FAVORITE_API = 'ADD_FAVORITE_API';
export const REMOVE_FAVORITE_API = 'REMOVE_FAVORITE_API';
export const CLEAR_FAVORITES_IN_REDUX = 'CLEAR_FAVORITES_IN_REDUX';
