export enum BusinessesQueryKeysWithFav {
  restaurantsWithMenu = 'restaurantsWithMenu',
  restaurants = 'restaurants',
  transport = 'transport',
  education = 'education',
  healthFitness = 'healthFitness',
  entertainment = 'entertainment',
  maintenanceAndServices = 'maintenanceAndServices',
  realEstate = 'realEstate',
  salons = 'salons',
  hardwareStore = 'hardwareStore',
  sewingAlterationsAndFabricStore = 'sewingAlterationsAndFabricStore',
  supermarketsShopping = 'supermarketsShopping',
  recentBusinesses = 'recentBusinesses',
}
