import { BusinessDetailBottomTabParamList } from './BusinessDetailBottomTabParamList';

export type MainStackParamList = {
  MainBottomTabNavigator: MainStackParamList;
  BusinessDetailTabNavigator: BusinessDetailBottomTabParamList;
  ThemeSetting: undefined;
  Setting: undefined;
  Category: undefined;
  Place: undefined;
  Walkthrough: undefined;
  SignUp: undefined;
  SignIn: undefined;
  Messenger: undefined;
  Messages: undefined;
  Feedback: undefined;
  ResetPassword: undefined;
  ChangePassword: undefined;
  ProfileEdit: undefined;
  ChangeLanguage: undefined;
  ContactUs: undefined;
  AboutUs: undefined;
  Address: undefined;
  Hours: undefined;
  PriceRange: undefined;
  FinalReview: undefined;
  Gallery: undefined;
  MyBusinesses: undefined;
  EditBusiness: undefined;
  VerifyCode: undefined;
};
