on:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v16.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: yarn install
        run: yarn install
      - name: tsc
        uses: icrawl/action-tsc@v1
